"""Markdown and HTML report generation."""

from __future__ import annotations

from pathlib import Path

import structlog

from aedm.models.schemas import (
    DemographicSegment,
    DriftResult,
    ExposureScore,
    Role,
    UrgencyScore,
)

logger = structlog.get_logger()


def _tier_badge(tier: str) -> str:
    """Return a text badge for the tier."""
    badges = {
        "Critical": "🔴 Critical",
        "High": "🟠 High",
        "Moderate": "🟡 Moderate",
        "Low": "🟢 Low",
    }
    return badges.get(tier, tier)


def generate_markdown_report(
    roles: list[Role],
    scores: list[ExposureScore],
    org_mean: float,
    dept_means: dict[str, float],
    urgency_scores: list[UrgencyScore] | None = None,
    demographic_segments: list[DemographicSegment] | None = None,
    drift_results: list[DriftResult] | None = None,
) -> str:
    """Generate a Markdown report summarizing the exposure analysis.

    Args:
        roles: List of Role objects.
        scores: List of ExposureScore objects.
        org_mean: Organization-wide mean exposure.
        dept_means: Department mean exposures.
        urgency_scores: Optional urgency scores.
        demographic_segments: Optional demographic analysis.
        drift_results: Optional drift analysis results.

    Returns:
        Markdown-formatted report string.
    """
    role_map = {r.role_id: r for r in roles}
    score_map = {s.role_id: s for s in scores}
    total_headcount = sum(r.headcount for r in roles)

    # Count by tier
    tier_counts = {"Critical": 0, "High": 0, "Moderate": 0, "Low": 0}
    tier_headcount = {"Critical": 0, "High": 0, "Moderate": 0, "Low": 0}
    for score in scores:
        tier_counts[score.tier.value] += 1
        role = role_map.get(score.role_id)
        if role:
            tier_headcount[score.tier.value] += role.headcount

    lines: list[str] = []

    # Header
    lines.append("# AI Exposure Analysis Report")
    lines.append("")
    lines.append("*Generated by AEDM — AI Exposure Drift Monitor*")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"- **Total roles analyzed:** {len(roles)}")
    lines.append(f"- **Total headcount:** {total_headcount:,}")
    lines.append(f"- **Organization mean exposure:** {org_mean:.1%}")
    lines.append("")
    lines.append("### Exposure Distribution by Tier")
    lines.append("")
    lines.append("| Tier | Roles | Headcount | % of Workforce |")
    lines.append("|------|-------|-----------|----------------|")
    for tier in ["Critical", "High", "Moderate", "Low"]:
        pct = tier_headcount[tier] / total_headcount * 100 if total_headcount > 0 else 0
        lines.append(
            f"| {_tier_badge(tier)} | {tier_counts[tier]} | "
            f"{tier_headcount[tier]:,} | {pct:.1f}% |"
        )
    lines.append("")

    # Department Overview
    lines.append("## Department Exposure")
    lines.append("")
    lines.append("| Department | Mean Exposure | Tier |")
    lines.append("|------------|---------------|------|")
    for dept, mean in sorted(dept_means.items(), key=lambda x: -x[1]):
        from aedm.models.enums import ExposureTier
        tier = ExposureTier.from_score(mean)
        lines.append(f"| {dept} | {mean:.1%} | {_tier_badge(tier.value)} |")
    lines.append("")

    # Top Exposed Roles
    lines.append("## Top 20 Most Exposed Roles")
    lines.append("")
    lines.append("| Rank | Title | Department | Exposure | Tier | Headcount |")
    lines.append("|------|-------|------------|----------|------|-----------|")
    sorted_scores = sorted(scores, key=lambda s: s.blended, reverse=True)
    for i, score in enumerate(sorted_scores[:20], 1):
        role = role_map.get(score.role_id)
        if role:
            lines.append(
                f"| {i} | {role.title} | {role.department} | "
                f"{score.blended:.1%} | {_tier_badge(score.tier.value)} | {role.headcount} |"
            )
    lines.append("")

    # Urgency
    if urgency_scores:
        lines.append("## Reskilling Urgency Rankings")
        lines.append("")
        lines.append("| Rank | Title | Department | Urgency Score | Tier | Headcount |")
        lines.append("|------|-------|------------|---------------|------|-----------|")
        for i, urgency in enumerate(urgency_scores[:20], 1):
            role = role_map.get(urgency.role_id)
            if role:
                lines.append(
                    f"| {i} | {role.title} | {role.department} | "
                    f"{urgency.score:.1%} | {_tier_badge(urgency.tier.value)} | {role.headcount} |"
                )
        lines.append("")

    # Demographics
    if demographic_segments:
        lines.append("## Demographic Disparity Analysis")
        lines.append("")
        flagged = [s for s in demographic_segments if s.flagged]
        if flagged:
            lines.append(f"**{len(flagged)} segment(s) flagged** for disproportionate exposure:")
            lines.append("")
            for seg in flagged:
                lines.append(
                    f"- **{seg.segment_value}** ({seg.segment_type}): "
                    f"{seg.disparity_ratio:.2f}x org mean, "
                    f"{seg.headcount:,} employees affected"
                )
            lines.append("")
        else:
            lines.append("No demographic segments exceed the disparity threshold.")
            lines.append("")

        lines.append("| Segment Type | Value | Mean Exposure | Disparity Ratio | Headcount | Flagged |")
        lines.append("|--------------|-------|---------------|-----------------|-----------|---------|")
        for seg in demographic_segments:
            flag = "⚠️ Yes" if seg.flagged else "No"
            lines.append(
                f"| {seg.segment_type} | {seg.segment_value} | "
                f"{seg.mean_exposure:.1%} | {seg.disparity_ratio:.2f}x | "
                f"{seg.headcount:,} | {flag} |"
            )
        lines.append("")

    # Drift
    if drift_results:
        lines.append("## Drift Analysis")
        lines.append("")
        accel = [d for d in drift_results if d.direction.value == "Accelerating"]
        decel = [d for d in drift_results if d.direction.value == "Decelerating"]
        stable = [d for d in drift_results if d.direction.value == "Stable"]
        lines.append(
            f"- **Accelerating:** {len(accel)} entities | "
            f"**Stable:** {len(stable)} | **Decelerating:** {len(decel)}"
        )
        lines.append("")
        lines.append("| Entity | Direction | Slope | p-value | Periods |")
        lines.append("|--------|-----------|-------|---------|---------|")
        for dr in sorted(drift_results, key=lambda d: abs(d.trend_slope), reverse=True):
            lines.append(
                f"| {dr.entity_id} | {dr.direction.value} | "
                f"{dr.trend_slope:+.4f} | {dr.p_value:.3f} | {dr.n_periods} |"
            )
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Report generated by [AEDM](https://github.com/ahwrist/ai-exposure-drift-monitor). ")
    lines.append("Methodology: Anthropic's theoretical + observed AI exposure framework.*")

    return "\n".join(lines)


def generate_html_report(
    markdown_content: str,
    chart_htmls: list[str] | None = None,
) -> str:
    """Wrap a Markdown report in an HTML template with optional charts.

    Args:
        markdown_content: The Markdown report content.
        chart_htmls: Optional list of Plotly chart HTML divs.

    Returns:
        Complete HTML document string.
    """
    try:
        import markdown as md
        html_body = md.markdown(markdown_content, extensions=["tables"])
    except ImportError:
        # Fallback: wrap markdown in pre tag
        html_body = f"<pre>{markdown_content}</pre>"

    charts_section = ""
    if chart_htmls:
        charts_section = "\n".join(
            f'<div class="chart">{chart}</div>' for chart in chart_htmls
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AEDM — AI Exposure Analysis Report</title>
    <style>
        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
            max-width: 1100px;
            margin: 0 auto;
            padding: 2rem;
            color: #1B2A4A;
            line-height: 1.6;
        }}
        h1 {{ color: #1B2A4A; border-bottom: 3px solid #2EC4B6; padding-bottom: 0.5rem; }}
        h2 {{ color: #1B2A4A; margin-top: 2rem; }}
        table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
        th, td {{ border: 1px solid #E8E8E8; padding: 0.5rem 0.75rem; text-align: left; }}
        th {{ background-color: #1B2A4A; color: white; }}
        tr:nth-child(even) {{ background-color: #f9f9f9; }}
        .chart {{ margin: 2rem 0; }}
        code {{ background: #f4f4f4; padding: 0.2rem 0.4rem; border-radius: 3px; }}
    </style>
</head>
<body>
{html_body}
{charts_section}
</body>
</html>"""


def save_report(
    content: str,
    output_path: Path,
) -> None:
    """Save report content to a file.

    Args:
        content: Report content (Markdown or HTML).
        output_path: Path to write the file.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)
    logger.info("report_saved", path=str(output_path))
